### ISSUE TITLE
Check and correct for sample-rate mismatches when loading the  `Sampler`

### ISSUE THREAD

**Issue by james-trayford** [james-trayford/strauss#7]
https://github.com/james-trayford/strauss/blob/82620a57723121233830f079dcc76ee43349fa00/src/strauss/generator.py#L560-L583

Should update to:

- Check sample rate against `Sonification` sample rate
- if different, scale `samps` appropriately to force it to conform to that rate at interpolation time

This will avoid spurious playback speed changes.

Could also consider migrating to `scipy` WAV reading for consistency with default write routine.

**Comment by SamYoules** [comment]
Set up sample-rate branch to address this.

**Comment by SamYoules** [comment]
I've made these changes to generator.py and utilities.py, but they are not fully tested yet. When you are back next week, it would be really useful to talk about the best way to handle testing.
